#NAME: gnb
#LAST DEPLOYED: Sat May  4 13:10:05 2024
#NAMESPACE: default
#STATUS: pending-install
#REVISION: 1
#TEST SUITE: None
#HOOKS:
#MANIFEST:
---
# Source: oai-gnb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oai-gnb-sa
---
# Source: oai-gnb/templates/configmap.yaml
#https://gitlab.eurecom.fr/oai/openairinterface5g/-/blob/develop/ci-scripts/conf_files/gnb.sa.band78.106prb.rfsim.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-gnb-configmap
data:
  gnb.conf: |
    Active_gNBs = ( "oai-gnb-rfsim");
    # Asn1_verbosity, choice in: none, info, annoying
    Asn1_verbosity = "none";
    gNBs =
    (
      {
        ////////// Identification parameters:
        gNB_ID    =  0xe00;
        gNB_name  =  "oai-gnb-rfsim";
        // Tracking area code, 0x0000 and 0xfffe are reserved values
        tracking_area_code  = 1 ;
        plmn_list = ({ mcc = 001; mnc = 01; mnc_length = 2; snssaiList = ({ sst = 1 }) });

        nr_cellid = 12345678L

    #     tr_s_preference     = "local_mac"

        ////////// Physical parameters:

        min_rxtxtime = 6;

          servingCellConfigCommon = (
          {
       #spCellConfigCommon

            physCellId                                                    = 0;

      #  downlinkConfigCommon
          #frequencyInfoDL
            # this is 3600 MHz + 43 PRBs@30kHz SCS (same as initial BWP)
            absoluteFrequencySSB                                          = 641280;
            dl_frequencyBand                                                 = 78;
            # this is 3600 MHz
            dl_absoluteFrequencyPointA                                       = 640008;
            #scs-SpecificCarrierList
              dl_offstToCarrier                                              = 0;
      # subcarrierSpacing
      # 0=kHz15, 1=kHz30, 2=kHz60, 3=kHz120  
              dl_subcarrierSpacing                                           = 1;
              dl_carrierBandwidth                                            = 106;
           #initialDownlinkBWP
            #genericParameters
              # this is RBstart=27,L=48 (275*(L-1))+RBstart
              initialDLBWPlocationAndBandwidth                               = 28875; # 6366 12925 12956 28875 12952
      # subcarrierSpacing
      # 0=kHz15, 1=kHz30, 2=kHz60, 3=kHz120  
              initialDLBWPsubcarrierSpacing                                           = 1;
            #pdcch-ConfigCommon
              initialDLBWPcontrolResourceSetZero                              = 12;
              initialDLBWPsearchSpaceZero                                             = 0;

        #uplinkConfigCommon 
           #frequencyInfoUL
            ul_frequencyBand                                                 = 78;
            #scs-SpecificCarrierList
            ul_offstToCarrier                                              = 0;
      # subcarrierSpacing
      # 0=kHz15, 1=kHz30, 2=kHz60, 3=kHz120  
            ul_subcarrierSpacing                                           = 1;
            ul_carrierBandwidth                                            = 106;
            pMax                                                          = 20;
           #initialUplinkBWP
            #genericParameters
              initialULBWPlocationAndBandwidth                            = 28875;
      # subcarrierSpacing
      # 0=kHz15, 1=kHz30, 2=kHz60, 3=kHz120  
              initialULBWPsubcarrierSpacing                                           = 1;
            #rach-ConfigCommon
              #rach-ConfigGeneric
                prach_ConfigurationIndex                                  = 98;
      #prach_msg1_FDM
      #0 = one, 1=two, 2=four, 3=eight
                prach_msg1_FDM                                            = 0;
                prach_msg1_FrequencyStart                                 = 0;
                zeroCorrelationZoneConfig                                 = 13;
                preambleReceivedTargetPower                               = -96;
      #preamblTransMax (0...10) = (3,4,5,6,7,8,10,20,50,100,200)
                preambleTransMax                                          = 6;
      #powerRampingStep
      # 0=dB0,1=dB2,2=dB4,3=dB6
              powerRampingStep                                            = 1;
      #ra_ReponseWindow
      #1,2,4,8,10,20,40,80
              ra_ResponseWindow                                           = 4;
      #ssb_perRACH_OccasionAndCB_PreamblesPerSSB_PR
      #1=oneeighth,2=onefourth,3=half,4=one,5=two,6=four,7=eight,8=sixteen
              ssb_perRACH_OccasionAndCB_PreamblesPerSSB_PR                = 4;
      #oneHalf (0..15) 4,8,12,16,...60,64
              ssb_perRACH_OccasionAndCB_PreamblesPerSSB                   = 14;
      #ra_ContentionResolutionTimer
      #(0..7) 8,16,24,32,40,48,56,64
              ra_ContentionResolutionTimer                                = 7;
              rsrp_ThresholdSSB                                           = 19;
      #prach-RootSequenceIndex_PR
      #1 = 839, 2 = 139
              prach_RootSequenceIndex_PR                                  = 2;
              prach_RootSequenceIndex                                     = 1;
              # SCS for msg1, can only be 15 for 30 kHz < 6 GHz, takes precendence over the one derived from prach-ConfigIndex
              #  
              msg1_SubcarrierSpacing                                      = 1,
      # restrictedSetConfig
      # 0=unrestricted, 1=restricted type A, 2=restricted type B
              restrictedSetConfig                                         = 0,

              msg3_DeltaPreamble                                          = 1;
              p0_NominalWithGrant                                         =-90;

      # pucch-ConfigCommon setup :
      # pucchGroupHopping
      # 0 = neither, 1= group hopping, 2=sequence hopping
              pucchGroupHopping                                           = 0;
              hoppingId                                                   = 40;
              p0_nominal                                                  = -90;
      # ssb_PositionsInBurs_BitmapPR
      # 1=short, 2=medium, 3=long
            ssb_PositionsInBurst_PR                                       = 2;
            ssb_PositionsInBurst_Bitmap                                   = 1;

      # ssb_periodicityServingCell
      # 0 = ms5, 1=ms10, 2=ms20, 3=ms40, 4=ms80, 5=ms160, 6=spare2, 7=spare1 
            ssb_periodicityServingCell                                    = 2;

      # dmrs_TypeA_position
      # 0 = pos2, 1 = pos3
            dmrs_TypeA_Position                                           = 0;

      # subcarrierSpacing
      # 0=kHz15, 1=kHz30, 2=kHz60, 3=kHz120  
            subcarrierSpacing                                             = 1;


        #tdd-UL-DL-ConfigurationCommon
      # subcarrierSpacing
      # 0=kHz15, 1=kHz30, 2=kHz60, 3=kHz120  
            referenceSubcarrierSpacing                                    = 1;
            # pattern1 
            # dl_UL_TransmissionPeriodicity
            # 0=ms0p5, 1=ms0p625, 2=ms1, 3=ms1p25, 4=ms2, 5=ms2p5, 6=ms5, 7=ms10
            dl_UL_TransmissionPeriodicity                                 = 6;
            nrofDownlinkSlots                                             = 7;
            nrofDownlinkSymbols                                           = 6;
            nrofUplinkSlots                                               = 2;
            nrofUplinkSymbols                                             = 4;

            ssPBCH_BlockPower                                             = -25;
           }

        );

        # ------- SCTP definitions
        SCTP :
        {
            # Number of streams to use in input/output
            SCTP_INSTREAMS  = 2;
            SCTP_OUTSTREAMS = 2;
        };

        ////////// AMF parameters:
        amf_ip_address      = ( { ipv4       = "@AMF_IP_ADDRESS@";
                                  ipv6       = "192:168:30::17";
                                  active     = "yes";
                                  preference = "ipv4";
                                }
                              );


        NETWORK_INTERFACES :
        {
          GNB_INTERFACE_NAME_FOR_NG_AMF            = "eth0";
          GNB_IPV4_ADDRESS_FOR_NG_AMF              = "@N2_IP_ADDRESS@";
          GNB_INTERFACE_NAME_FOR_NGU               = "n3";
          GNB_IPV4_ADDRESS_FOR_NGU                 = "@N3_IP_ADDRESS@";
          GNB_PORT_FOR_S1U                         = 2152; # Spec 2152
        };
      }
    );

    MACRLCs = (
      {
        num_cc           = 1;
        tr_s_preference  = "local_L1";
        tr_n_preference  = "local_RRC";
        pusch_TargetSNRx10 = 200;
        pucch_TargetSNRx10 = 200;
      }
    );

    L1s = (
    {
      num_cc = 1;
      tr_n_preference = "local_mac";
      prach_dtx_threshold = 200;
    #  pucch0_dtx_threshold = 150;
    }
    );

    RUs = (
        {
           local_rf       = "yes"
             nb_tx          = 1
             nb_rx          = 1
             att_tx         = 0
             att_rx         = 0;
             bands          = [78];
             max_pdschReferenceSignalPower = -27;
             max_rxgain                    = 75;
             eNB_instances  = [0];
             ##beamforming 1x2 matrix: 1 layer x 2 antennas
             bf_weights = [0x00007fff, 0x0000];
             ##beamforming 1x4 matrix: 1 layer x 4 antennas
             #bf_weights = [0x00007fff, 0x0000,0x0000, 0x0000];
             ## beamforming 2x2 matrix:
             # bf_weights = [0x00007fff, 0x00000000, 0x00000000, 0x00007fff];
             ## beamforming 4x4 matrix:
             #bf_weights = [0x00007fff, 0x0000, 0x0000, 0x0000, 0x00000000, 0x00007fff, 0x0000, 0x0000, 0x0000, 0x0000, 0x00007fff, 0x0000, 0x0000, 0x0000, 0x0000, 0x00007fff];
             sf_extension = 0
             sdr_addrs = "serial=XXXXXXX"
        }
    );

    THREAD_STRUCT = (
      {
        #three config for level of parallelism "PARALLEL_SINGLE_THREAD", "PARALLEL_RU_L1_SPLIT", or "PARALLEL_RU_L1_TRX_SPLIT"
        parallel_config    = "PARALLEL_SINGLE_THREAD";
        #two option for worker "WORKER_DISABLE" or "WORKER_ENABLE"
        worker_config      = "WORKER_ENABLE";
      }
    );

    rfsimulator: {
        serveraddr = "server";
    };

    security = {
      # preferred ciphering algorithms
      # the first one of the list that an UE supports in chosen
      # valid values: nea0, nea1, nea2, nea3
      ciphering_algorithms = ( "nea0" );

      # preferred integrity algorithms
      # the first one of the list that an UE supports in chosen
      # valid values: nia0, nia1, nia2, nia3
      integrity_algorithms = ( "nia2", "nia0" );

      # setting 'drb_ciphering' to "no" disables ciphering for DRBs, no matter
      # what 'ciphering_algorithms' configures; same thing for 'drb_integrity'
      drb_ciphering = "yes";
      drb_integrity = "no";
    };

    log_config :
      {
        global_log_level                      ="info";
        hw_log_level                          ="info";
        phy_log_level                         ="info";
        mac_log_level                         ="info";
        rlc_log_level                         ="info";
        pdcp_log_level                        ="info";
        rrc_log_level                         ="info";
        f1ap_log_level                         ="debug";
      };
---
# Source: oai-gnb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: oai-ran
  labels:
    helm.sh/chart: oai-gnb-2.0.0
    app.kubernetes.io/name: oai-gnb
    app.kubernetes.io/instance: gnb
    app.kubernetes.io/version: "develop"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: n3
      port: 2152
      targetPort: 2152
      protocol: UDP
    - name: n2
      port: 36412
      targetPort: 36412
      protocol: SCTP
  selector:
    app.kubernetes.io/name: oai-gnb
    app.kubernetes.io/instance: gnb
---
# Source: oai-gnb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-gnb
  labels:
    helm.sh/chart: oai-gnb-2.0.0
    app.kubernetes.io/name: oai-gnb
    app.kubernetes.io/instance: gnb
    app.kubernetes.io/version: "develop"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oai-gnb
      app.kubernetes.io/instance: gnb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oai-gnb
        app.kubernetes.io/instance: gnb
        app: oai-gnb
    spec:
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      imagePullSecrets:
                - name: regcred
      containers:
      - name: gnb
        image: "docker.io/oaisoftwarealliance/oai-gnb:2023.w49"
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /opt/oai-gnb/etc
            name: configuration
            # subPath: gnb.conf
          # USRP B210/B200 Mini
        securityContext:
           privileged: true
           # capabilities:
           #    add:
           #     - NET_ADMIN
           #    drop:
           #     - ALL
        ports:
        - containerPort: 2152
          name: n3
          protocol: UDP
        - containerPort: 36412
          name: n2
          protocol: SCTP
        command: [ "/bin/bash", "-c" ]
        args:
         -  AMF_IP_ADDRESS=$(getent hosts $AMF_HOST | awk '{print $1}');
            AMF_IP_ADDRESS=$(if [[ $AMF_IP_ADDRESS ]]; then echo $AMF_IP_ADDRESS; else echo $AMF_HOST;fi);
            N2_IP_ADDRESS=$(ip -f inet addr show $N2_IF_NAME | grep -o "inet [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*");
            N3_IP_ADDRESS=$(ip -f inet addr show $N3_IF_NAME | grep -o "inet [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*");
            sed -e s/@N2_IP_ADDRESS@/$N2_IP_ADDRESS/g
                -e s/@N3_IP_ADDRESS@/$N3_IP_ADDRESS/g
                -e s/@AMF_IP_ADDRESS@/$AMF_IP_ADDRESS/g
                /opt/oai-gnb/etc/gnb.conf | tee /tmp/gnb.conf;
            exec /opt/oai-gnb/bin/nr-softmodem -O /tmp/gnb.conf $USE_ADDITIONAL_OPTIONS;
        env:
          - name: TZ
            value: Europe/Paris
          - name: USE_ADDITIONAL_OPTIONS
            value: --sa --rfsim --log_config.global_log_options level,nocolor,time
          - name: AMF_HOST
            value: oai-amf
          - name: N2_IF_NAME
            value: eth0
          - name: N3_IF_NAME
            value: n3
      volumes:
      - configMap:
          name: oai-gnb-configmap
        name: configuration
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: oai-gnb-sa
      terminationGracePeriodSeconds: 5
---
# Source: oai-gnb/templates/multus.yaml
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: oai-gnb-n3
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master":"eth0",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address":"172.21.8.91/22"
                }
        ]
      }
    }'

    #NOTES:
  #1. Get the application name by running these commands:
  #export GNB_POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=oai-gnb,app.kubernetes.io/instance=gnb" -o jsonpath="{.items[0].metadata.name}")
  #export GNB_eth0_IP=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=oai-gnb,app.kubernetes.io/instance=gnb" -o jsonpath="{.items[*].status.podIP}")
  #2. Dockerhub images of OpenAirInterface requires avx2 capabilities in the cpu and they are built for x86 architecture, tested on UBUNTU OS only.
#3. Note: This helm chart of OAI-gNB is only tested in RF-simulator mode and is not tested with USRPs/RUs on Openshift/Kubernetes Cluster
  #4. In case you want to test these charts with USRP/RU then make sure your underlying kernel is realtime and CPU sleep states are off. 
  #Also for good performance it is better to use MTU 9000 for Fronthaul interface. 
   #5. If you want to configure for a particular band then copy the configuration file in templates/configmap.yaml from here https://gitlab.eurecom.fr/oai/openairinterface5g/-/tree/develop/targets/PROJECTS/GENERIC-NR-5GC/CONF
